<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SimpleBitware.Common.Abstractions</PackageId>
    <Description>Abstrations for commonly used .net static classes</Description>
    <Authors>Lucian Bornaz</Authors>
    <Company>Simple Bitware</Company>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/SimpleBitware/Common</RepositoryUrl>
    <PackageProjectUrl>https://github.com/SimpleBitware/Common/tree/main/src/SimpleBitware.Common.Abstractions</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>logo.png</PackageIcon>

    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <MinVerTagPrefix>v</MinVerTagPrefix>
  </PropertyGroup>

  <PropertyGroup>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md"
          Pack="true"
          PackagePath=""
          Visible="false"/>
    <None Include="..\..\resources\logo.png"
          Pack="true"
          PackagePath=""
          Visible="false"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MinVer" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
